name: Build

on:
  #schedule:
    # update the images every morning
    #- cron: "0 0 * * *"
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v7
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push lancachenet/ubuntu
        run: |
          git clone https://github.com/lancachenet/ubuntu.git
          cd ubuntu
          docker buildx build --platform linux/arm/v7,linux/arm64 -t jrcichra/lancachenet-ubuntu --push .
          cd ..
      - name: Build & Push lancachenet/ubuntu-nginx
        run: |
          git clone https://github.com/lancachenet/ubuntu-nginx.git
          cd ubuntu-nginx
          sed -i '1cFROM jrcichra/lancachenet-ubuntu' Dockerfile
          cat Dockerfile
          docker buildx build --platform linux/arm/v7,linux/arm64 -t jrcichra/lancachenet-ubuntu-nginx --push .
          cd ..
      - name: Build & Push lancachenet/generic
        run: |
          git clone https://github.com/lancachenet/generic.git
          cd generic
          sed -i '1cFROM jrcichra/lancachenet-ubuntu-nginx' Dockerfile
          cat Dockerfile
          docker buildx build --platform linux/arm/v7,linux/arm64 -t jrcichra/lancachenet-generic --push .
          cd ..
      - name: Build & Push lancachenet/monolithic
        run: |
          git clone https://github.com/lancachenet/monolithic.git
          cd monolithic
          sed -i '1cFROM jrcichra/lancachenet-generic' Dockerfile
          cat Dockerfile
          cp ../20_cache.conf overlay/etc/nginx/sites-available/cache.conf.d/root/20_cache.conf
          docker buildx build --platform linux/arm/v7,linux/arm64 -t jrcichra/lancachenet-monolithic --push .
          cd ..
      - name: Build & Push lancachenet/sniproxy
        run: |
          git clone https://github.com/lancachenet/sniproxy.git
          cd sniproxy
          docker buildx build --platform linux/arm/v7,linux/arm64 -t jrcichra/lancachenet-sniproxy --push .
          cd ..
      - name: Build & Push lancachenet/lancache-dns
        run: |
          git clone https://github.com/lancachenet/lancache-dns.git
          cd lancache-dns
          sed -i '1cFROM jrcichra/lancachenet-ubuntu' Dockerfile
          cat Dockerfile
          docker buildx build --platform linux/arm/v7,linux/arm64 -t jrcichra/lancachenet-lancache-dns --push .
          cd ..
